"""LLM-powered metadata enrichment for document chunks.

Each chunk is enriched with a summary, keywords, hypothetical questions,
and (for tables) a natural-language table summary.  Every LLM call is
traced by W&B Weave via the @weave_op decorator.
"""

from __future__ import annotations

import logging
from typing import Any, Optional

from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

from backend.config import get_settings
from backend.observability.weave_client import weave_op

logger = logging.getLogger(__name__)


# ── Pydantic schema the LLM must return ───────────────────────────────────────

class ChunkMetadata(BaseModel):
    """Structured metadata generated by the enrichment LLM."""

    summary: str = Field(description="A concise 1-2 sentence summary of the chunk.")
    keywords: list[str] = Field(description="5-7 key topics or entities mentioned.")
    hypothetical_questions: list[str] = Field(
        description="3-5 questions this chunk could answer."
    )
    table_summary: Optional[str] = Field(
        default=None,
        description=(
            "If the chunk is a table, a natural-language description of its "
            "key data and trends.  Null for non-table chunks."
        ),
    )


# ── Enrichment functions ───────────────────────────────────────────────────────

def _build_prompt(content: str, is_table: bool) -> str:
    table_hint = (
        "\nThis chunk is an HTML TABLE. Your table_summary must describe the "
        "key data points and trends (e.g. '15% YoY revenue growth in Cloud').\n"
        if is_table
        else ""
    )
    return (
        "You are an expert financial analyst. Analyse the following document "
        f"chunk and produce the requested metadata.{table_hint}\n"
        "Chunk Content:\n---\n"
        f"{content[:3000]}\n---"
    )


@weave_op()
def enrich_chunk(chunk_content: str, is_table: bool = False) -> dict[str, Any] | None:
    """Call the enrichment LLM for a single chunk and return its metadata dict.

    Returns None on failure so the caller can skip the chunk.
    """
    cfg = get_settings()
    llm = ChatOpenAI(
        model=cfg.enrichment_model,
        temperature=0,
        openai_api_key=cfg.openai_api_key,
    ).with_structured_output(ChunkMetadata)

    prompt = _build_prompt(chunk_content, is_table)
    try:
        result: ChunkMetadata = llm.invoke(prompt)
        return result.model_dump()
    except Exception as exc:
        logger.warning("Enrichment failed: %s", exc)
        return None


@weave_op()
def enrich_chunks_batch(
    chunks: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Enrich a list of raw chunk dicts (each must have 'content' and 'is_table').

    Returns a new list of dicts with the enrichment metadata merged in,
    skipping any chunks where the LLM call failed.
    """
    enriched: list[dict[str, Any]] = []
    for chunk in chunks:
        content = chunk.get("content", "")
        is_table = chunk.get("is_table", False)
        meta = enrich_chunk(content, is_table)
        if meta:
            enriched.append({**chunk, **meta})
        else:
            logger.debug("Skipping chunk (enrichment returned None)")
    return enriched
